server:
  error:
    include-stacktrace: never
spring:
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/movie?useSSL=false&&serverTimezone=IST
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver